### ISSUE TITLE
Sloth overrides styling

### ISSUE THREAD

**Issue by pieterbeulque** [mrhenry/sloth#8]
Setting `position: absolute` or a specific `z-index` on `.sloth__content` when using a `BackgroundSloth` instance doesn't work because Sloth will set inline styles: `position: relative; z-index: 2;` on the element when executing `wrap()`.

A bugfix is to override it with `!important` as follows:

```css
.sloth__content[style] {
  position: absolute !important;
  z-index: 99 !important;
}
```
